# 该镜像需要依赖的基础镜像
FROM openjdk:8
# 将当前目录下的jar包复制到docker容器的/目录下
ADD intelligence-education-0.0.1-SNAPSHOT.jar /intelligence-education.jar
# 运行过程中创建一个.jar文件
RUN bash -c 'touch /intelligence-education.jar'
# 声明服务运行在8081端口
EXPOSE 8081
# 指定docker容器启动时运行jar包
ENTRYPOINT ["java", "-jar","/intelligence-education.jar"]
# 指定维护者的名字
MAINTAINER gaochuchu
