# 项目相关配置
base:
  # 名称
  name: Base
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/base/uploadPath，Linux配置 /home/base/uploadPath）
  profile: /home/base/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.base: info
#    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


## MyBatis配置
#mybatis:
##    # 搜索指定包别名
##    typeAliasesPackage: com.gcc.**.pojo
##    # 配置mapper的扫描，找到所有的mapper.xml映射文件
##    mapperLocations: classpath*:com/gcc/mapper/**/*.xml
##    # 加载全局的配置文件
##    configLocation: classpath:mybatis/mybatis-config.xml
mybatis-plus:
  mapper-locations: classpath*:com/gcc/mapper/**/*.xml
  map-underscore-to-camel-case: true

#
## PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  autoRuntimeDialect: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /swagger-ui

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice,/tool/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*


scheduled:
  switchs: false
  # 用户数据同步
  syncHasQzTask: 0 0 22 * * ?
  syncNoHasQzTask: 0 0 22 * * ?
  onceADay: 0 0 22 * * ?
  onceADayAtMidday: 0 0 22 * * ?
  onceAWeek: 0 23 0 ? * MON

interact:
  app_key: u1sSAMNPR5G45uDT5Sm2eA==
  secret_key: 92c904ab607eaac9d70098212e4a440f

kafka:
  enabled: false